name: Sync Forks
# adapted from CCBR/.github: https://github.com/CCBR/.github/blob/b51390632d8093aa2a3c8cbb871a2f2b5c7d5aae/.github/workflows/sync-forks.yml

on:
  schedule:
    - cron: "23 10 * * *" # once every day
  push:
    paths:
      - .github/workflows/sync-forks.yml
  workflow_dispatch:

permissions:
  contents: write

env:
  UPSTREAM_OWNER: NCI-RBL

jobs:
  sync:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        FORK_OWNER: [abcsFrederick]
        REPO:
          [
            { upstream: iCLIP_V3, fork: iCLIP_V3 },
            { upstream: Dockers, fork: NCI-RBL-Dockers },
          ]

    steps:
      - name: Generate a token
        id: generate-token
        uses: actions/create-github-app-token@v2
        with:
          app-id: ${{ vars.CCBR_BOT_APP_ID }}
          private-key: ${{ secrets.CCBR_BOT_PRIVATE_KEY }}
          owner: ${{ matrix.FORK_OWNER }}
      - name: sync forked repos
        env:
          GH_TOKEN: ${{ steps.generate-token.outputs.token }}
        run: |
          gh repo sync ${{ matrix.FORK_OWNER }}/${{ matrix.REPO.fork }} --source $UPSTREAM_OWNER/${{ matrix.REPO.upstream }} --force
